version: '3.8'

services:
  db:
    image: mysql:8.0 
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: BeATiger
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: AGoodPassword
    ports:
      - "4955:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_ui
    restart: always
    ports:
      - "8000:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: BeATiger
    depends_on:
      - db

volumes:
  db_data: